
CREATE TABLE ORDERS (
    ORDER_ID NUMBER,
    CUSTOMER_ID NUMBER,
    ORDER_DATE DATE,
    AMOUNT NUMBER
);

CREATE TABLE CUSTOMERS (
    CUSTOMER_ID NUMBER,
    NAME VARCHAR2(100),
    EMAIL VARCHAR2(100),
    CREATED_DATE DATE
);
